// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';

export function BrowseFolder():Promise<string>;

export function CheckForUpdate():Promise<types.UpdateInfo>;

export function FetchRemoteManifest(arg1:string):Promise<types.RemoteManifest>;

export function GetBackupExamplePath():Promise<string>;

export function GetBackupRoot():Promise<string>;

export function GetDefaultCodexDir():Promise<string>;

export function GetLocalIPs():Promise<Array<string>>;

export function InspectCodexDir(arg1:string):Promise<types.CodexInspection>;

export function OpenFolder(arg1:string):Promise<void>;

export function OpenURL(arg1:string):Promise<void>;

export function StartSharing(arg1:types.ShareRequest):Promise<types.ShareStatus>;

export function StopSharing():Promise<void>;

export function SyncFromPeer(arg1:types.SyncRequest):Promise<types.SyncResult>;

export function TestConnection(arg1:string):Promise<types.PeerStatus>;
