// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BrowseFolder() {
  return window['go']['main']['App']['BrowseFolder']();
}

export function FetchRemoteManifest(arg1) {
  return window['go']['main']['App']['FetchRemoteManifest'](arg1);
}

export function GetBackupExamplePath() {
  return window['go']['main']['App']['GetBackupExamplePath']();
}

export function GetBackupRoot() {
  return window['go']['main']['App']['GetBackupRoot']();
}

export function GetDefaultCodexDir() {
  return window['go']['main']['App']['GetDefaultCodexDir']();
}

export function GetLocalIPs() {
  return window['go']['main']['App']['GetLocalIPs']();
}

export function InspectCodexDir(arg1) {
  return window['go']['main']['App']['InspectCodexDir'](arg1);
}

export function OpenFolder(arg1) {
  return window['go']['main']['App']['OpenFolder'](arg1);
}

export function StartSharing(arg1) {
  return window['go']['main']['App']['StartSharing'](arg1);
}

export function StopSharing() {
  return window['go']['main']['App']['StopSharing']();
}

export function SyncFromPeer(arg1) {
  return window['go']['main']['App']['SyncFromPeer'](arg1);
}

export function TestConnection(arg1) {
  return window['go']['main']['App']['TestConnection'](arg1);
}
